config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/index'
  get 'admin/edit'
  patch 'admin/update'
  devise_for :users
  resources :photos do
    member do
      get 'preview'
    end
  end
  resources :depenses do
    member do
      get 'destroy_attachement'
    end
  end
  resources :devis_lignes
  resources :facture_lignes
  resources :devis do
    member do
      get 'duplicate'
    end
  end
  resources :factures do
    member do
      get 'duplicate'
    end
  end
  resources :clients
  resources :document_modeles
  resources :devis_statuts
  resources :facture_statuts
  resources :taxes
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/edit.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(admin_index_path) %>
  <%= page_title("Modifier mon entreprise") %>
</nav>

<div class=" one-page-form">
  <%= form_with(model: @user, url: admin_update_path) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label "Code NAF/APE", class: "label" %>
      <div class="control">
        <%= form.text_field :code_naf_ape, class: "input" %>
      </div>
    </div>
    <div class="field">
      <%= form.label "TVA intracom.", class: "label" %>
      <div class="control">
        <%= form.text_field :numero_tva, class: "input" %>
      </div>
    </div>
    <div class="field">
      <%= form.label "SIREN", class: "label" %>
      <div class="control">
        <%= form.text_field :numero_siren, class: "input" %>
      </div>
    </div>
    <div class="field">
      <%= form.label "SIRET", class: "label" %>
      <div class="control">
        <%= form.text_field :numero_siret, class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :dernier_numero_facture, class: "label" %>
      <div class="control">
        <%= form.text_field :dernier_numero_facture, class: "input" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :dernier_numero_devis, class: "label" %>
      <div class="control">
        <%= form.text_field :dernier_numero_devis, class: "input" %>
      </div>
    </div>


    <div class="field is-grouped is-grouped-right">
      <div class="control">
        <%= form.submit "Enregistrer", class: "button is-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/index.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to_root() %>
  <%= page_title("Mon entreprise") %>
</nav>

<div class="small-width-page">
  <div class="box">
    <table class="table has-text-left is-hoverable is-fullwidth">
      <tr>
        <th>Code NAF/APE</th>
        <td><%= @user.code_naf_ape %></td>
        <td></td>
      </tr>
      <tr>
        <th>TVA intracom.</th>
        <td><%= @user.numero_tva %></td>
        <td><%= button_to_copy(@user.numero_tva) %></td>
      </tr>
      <tr>
        <th>SIREN</th>
        <td><%= @user.numero_siren %></td>
        <td><%= button_to_copy(@user.numero_siren) %></td>
      </tr>
      <tr>
        <th>SIRET</th>
        <td><%= @user.numero_siret %></td>
        <td><%= button_to_copy(@user.numero_siret) %></td>
      </tr>
      <tr>
        <th>Prochain n° de facture</th>
        <td><%= @user.dernier_numero_facture %></td>
        <td></td>
      </tr>
      <tr>
        <th>Prochain n° de devis</th>
        <td><%= @user.dernier_numero_devis %></td>
        <td></td>
      </tr>
    </table>
    <div class="field is-grouped is-grouped-right">
        <%= link_to 'Modifier', admin_edit_path, class: "button is-primary" %>
    </div>
  </div>
</div>