config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/index'
  get 'admin/edit'
  patch 'admin/update'
  devise_for :users
  resources :photos do
    member do
      get 'preview'
    end
  end
  resources :depenses do
    member do
      get 'destroy_attachement'
    end
  end
  resources :devis_lignes
  resources :facture_lignes
  resources :devis do
    member do
      get 'duplicate'
    end
  end
  resources :factures do
    member do
      get 'duplicate'
    end
  end
  resources :clients
  resources :document_modeles
  resources :devis_statuts
  resources :facture_statuts
  resources :taxes
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/devis_statut.rb
class DevisStatut < ApplicationRecord
  validates :nom,  :presence => true
  belongs_to :user
end

app/controllers/devis_statuts_controller.rb
class DevisStatutsController < ApplicationController
  before_action :set_devis_statut, only: %i[ show edit update destroy ]

  # GET /devis_statuts or /devis_statuts.json
  def index
    @devis_statuts = current_user.devis_statuts
  end

  # GET /devis_statuts/1 or /devis_statuts/1.json
  def show
  end

  # GET /devis_statuts/new
  def new
    @devis_statut = DevisStatut.new
  end

  # GET /devis_statuts/1/edit
  def edit
  end

  # POST /devis_statuts or /devis_statuts.json
  def create
    @devis_statut = DevisStatut.new(devis_statut_params)
    @devis_statut.user = current_user

    respond_to do |format|
      if @devis_statut.save
        format.html { redirect_to edit_devis_statut_path(@devis_statut), notice: "Devis statut was successfully created." }
        format.json { render :show, status: :created, location: @devis_statut }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @devis_statut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devis_statuts/1 or /devis_statuts/1.json
  def update
    respond_to do |format|
      if @devis_statut.update(devis_statut_params)
        format.html { redirect_to edit_devis_statut_path(@devis_statut), notice: "Devis statut was successfully updated." }
        format.json { render :show, status: :ok, location: @devis_statut }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @devis_statut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devis_statuts/1 or /devis_statuts/1.json
  def destroy
    @devis_statut.destroy
    respond_to do |format|
      format.html { redirect_to devis_statuts_url, notice: "Devis statut was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devis_statut
      @devis_statut = DevisStatut.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def devis_statut_params
      params.require(:devis_statut).permit(:nom, :defaut)
    end
end

app/helpers/devis_statuts_helper.rb
module DevisStatutsHelper
end

app/views/devis_statuts/_form.html.erb
<%= form_with(model: devis_statut) do |form| %>
  <% if devis_statut.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(devis_statut.errors.count, "error") %> prohibited this devis_statut from being saved:</h2>

      <ul>
        <% devis_statut.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom, class: "label" %>
    <div class="control">
      <%= form.text_field :nom, class: "input" %>
    </div>
  </div>

  <div class="field">
    <label class="checkbox">
      <%= form.check_box :defaut, class: "checkbox" %> Par défaut
    </label>
  </div>

  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= form.submit "Enregistrer", class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/devis_statuts/edit.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(devis_statuts_path) %>
  <%= page_title("Modifier le statut de devis") %>
</nav>

<div class="one-page-form">
    <%= render 'form', devis_statut: @devis_statut %>
</div>

app/views/devis_statuts/index.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to_root() %>
  <%= page_title("Statuts pour les devis") %>
</nav>

<div class="action-buttons">
    <div class="field is-grouped">
      <p class="control">
        <%= link_to 'Nouveau statut', new_devis_statut_path, class: "button is-primary" %>
      </p>
    </div>
</div>

<table class="table is-fullwidth is-hoverable">
  <thead>
    <tr>
      <th class="has-text-left">Nom</th>
      <th>Défaut</th>
    </tr>
  </thead>

  <tbody>
    <% @devis_statuts.each do |devis_statut| %>
      <tr class='clickable-row is-clickable' data-href='<%= url_for edit_devis_statut_path(devis_statut)%>'>
        <td><%= devis_statut.nom %></td>
        <td class="has-text-centered">
          <% if devis_statut.defaut %>
          <span class="icon"><i class="fa fa-check"></i></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devis_statuts/new.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(devis_statuts_path) %>
  <%= page_title("Nouvelle statut de devis") %>
</nav>

<div class="one-page-form">
    <%= render 'form', devis_statut: @devis_statut %>
</div>

app/views/devis_statuts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @devis_statut.nom %>
</p>

<p>
  <strong>Défaut:</strong>
  <%= @devis_statut.defaut %>
</p>

<%= link_to 'Edit', edit_devis_statut_path(@devis_statut) %> |
<%= link_to 'Back', devis_statuts_path %>