config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/index'
  get 'admin/edit'
  patch 'admin/update'
  devise_for :users
  resources :photos do
    member do
      get 'preview'
    end
  end
  resources :depenses do
    member do
      get 'destroy_attachement'
    end
  end
  resources :devis_lignes
  resources :facture_lignes
  resources :devis do
    member do
      get 'duplicate'
    end
  end
  resources :factures do
    member do
      get 'duplicate'
    end
  end
  resources :clients
  resources :document_modeles
  resources :devis_statuts
  resources :facture_statuts
  resources :taxes
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document_modele.rb
class DocumentModele < ApplicationRecord
  validates :nom,  :presence => true
  belongs_to :user
end

app/controllers/document_modeles_controller.rb
class DocumentModelesController < ApplicationController
  before_action :set_document_modele, only: %i[ show edit update destroy ]

  # GET /document_modeles or /document_modeles.json
  def index
    @document_modeles = current_user.document_modeles
  end

  # GET /document_modeles/1 or /document_modeles/1.json
  def show
  end

  # GET /document_modeles/new
  def new
    @document_modele = DocumentModele.new
  end

  # GET /document_modeles/1/edit
  def edit
  end

  # POST /document_modeles or /document_modeles.json
  def create
    @document_modele = DocumentModele.new(document_modele_params)
    @document_modele.user = current_user

    respond_to do |format|
      if @document_modele.save
        format.html { redirect_to edit_document_modele_path(@document_modele), notice: "Document modele was successfully created." }
        format.json { render :show, status: :created, location: @document_modele }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document_modele.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_modeles/1 or /document_modeles/1.json
  def update
    respond_to do |format|
      if @document_modele.update(document_modele_params)
        format.html { redirect_to edit_document_modele_path(@document_modele), notice: "Document modele was successfully updated." }
        format.json { render :show, status: :ok, location: @document_modele }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document_modele.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_modeles/1 or /document_modeles/1.json
  def destroy
    @document_modele.destroy
    respond_to do |format|
      format.html { redirect_to document_modeles_url, notice: "Document modele was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_modele
      @document_modele = DocumentModele.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_modele_params
      params.require(:document_modele).permit(:nom, :defaut, :date_reglement, :date_validite, :coordonnees_societe, :logo, :mention1_texte, :mention2_texte, :mention3_texte, :mention_legale, :contrast_color)
    end
end

app/helpers/document_modeles_helper.rb
module DocumentModelesHelper
end

app/views/document_modeles/_form.html.erb
<%= form_with(model: document_modele) do |form| %>
  <% if document_modele.errors.any? %>
    <div class="notification is-danger">
      <h2 class="is-size-5"><%= pluralize(document_modele.errors.count, "error") %> prohibited this document_modele from being saved:</h2>
      <div class="content">
      <ul>
        <% document_modele.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom, class: "label" %>
    <div class="control">
      <%= form.text_field :nom, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :date_validite, class: "label" %>
    <div class="control">
      <%= form.text_field :date_validite, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :date_reglement, class: "label" %>
    <div class="control">
      <%= form.text_field :date_reglement, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :coordonnees_societe, class: "label" %>
    <div class="control">
      <%= form.text_area :coordonnees_societe, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :logo, class: "label" %>
    <div class="control">
      <%= form.text_field :logo, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :contrast_color, class: "label" %>
    <div class="control">
      <%= form.text_field :contrast_color, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :mention1_texte, class: "label" %>
    <div class="control">
      <%= form.text_area :mention1_texte, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :mention2_texte, class: "label" %>
    <div class="control">
      <%= form.text_area :mention2_texte, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :mention3_texte, class: "label" %>
    <div class="control">
      <%= form.text_area :mention3_texte, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :mention_legale, class: "label" %>
    <div class="control">
      <%= form.text_area :mention_legale, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <label class="checkbox">
      <%= form.check_box :defaut, class: "checkbox" %> Par défaut
    </label>
  </div>

  <div class="field is-grouped is-grouped-right">
    <div class="control">
      <%= form.submit "Enregistrer", class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/document_modeles/edit.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(document_modeles_path) %>
  <%= page_title("Modifier le modèle de document") %>
</nav>

<div class="one-page-form">
    <%= render 'form', document_modele: @document_modele %>
</div>

app/views/document_modeles/index.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to_root() %>
  <%= page_title("Modèles de documents") %>
</nav>

<div class="action-buttons">
    <div class="field is-grouped">
      <p class="control">
        <%= link_to 'Nouveau modèle', new_document_modele_path, class: "button is-primary" %>
      </p>
    </div>
</div>

<table class="table is-fullwidth is-hoverable">
  <thead>
    <tr>
      <th class="has-text-left">Nom</th>
      <th class="has-text-left">Logo</th>
      <th class="has-text-left">Couleur</th>
      <th>Défaut</th>
    </tr>
  </thead>

  <tbody>
    <% @document_modeles.each do |document_modele| %>
      <tr class='clickable-row is-clickable' data-href='<%= url_for edit_document_modele_path(document_modele)%>'>
        <td><%= document_modele.nom %></td>
        <td><%= document_modele.logo %></td>
        <td><%= document_modele.contrast_color %></td>
        <td class="has-text-centered">
          <% if document_modele.defaut %>
          <span class="icon"><i class="fa fa-check"></i></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/document_modeles/new.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(document_modeles_path) %>
  <%= page_title("Nouveau modèle de document") %>
</nav>

<div class="one-page-form">
    <%= render 'form', document_modele: @document_modele %>
</div>

app/views/document_modeles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @document_modele.nom %>
</p>

<p>
  <strong>Coordonnees societe:</strong>
  <%= @document_modele.coordonnees_societe %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @document_modele.logo %>
</p>

<p>
  <strong>Mention1 texte:</strong>
  <%= @document_modele.mention1_texte %>
</p>

<p>
  <strong>Mention1 active:</strong>
  <%= @document_modele.mention1_active %>
</p>

<p>
  <strong>Mention2 texte:</strong>
  <%= @document_modele.mention2_texte %>
</p>

<p>
  <strong>Mention2 active:</strong>
  <%= @document_modele.mention2_active %>
</p>

<p>
  <strong>Mention3 texte:</strong>
  <%= @document_modele.mention3_texte %>
</p>

<p>
  <strong>Mention3 active:</strong>
  <%= @document_modele.mention3_active %>
</p>

<p>
  <strong>Mention legale:</strong>
  <%= @document_modele.mention_legale %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @document_modele.modele %>
</p>

<%= link_to 'Edit', edit_document_modele_path(@document_modele) %> |
<%= link_to 'Back', document_modeles_path %>