config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/index'
  get 'admin/edit'
  patch 'admin/update'
  devise_for :users
  resources :photos do
    member do
      get 'preview'
    end
  end
  resources :depenses do
    member do
      get 'destroy_attachement'
    end
  end
  resources :devis_lignes
  resources :facture_lignes
  resources :devis do
    member do
      get 'duplicate'
    end
  end
  resources :factures do
    member do
      get 'duplicate'
    end
  end
  resources :clients
  resources :document_modeles
  resources :devis_statuts
  resources :facture_statuts
  resources :taxes
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/devi.rb
class Devi < ApplicationRecord
  belongs_to :taxe
  belongs_to :devis_statut
  belongs_to :client
  belongs_to :user
  has_many :devis_lignes, :foreign_key => "devis_id", inverse_of: :devis, dependent: :destroy

  accepts_nested_attributes_for :devis_lignes, :client, allow_destroy: true, reject_if: :all_blank

  before_validation :define_client_updated_at
  before_save :define_number_devis

  def client_current_version
    self.client.paper_trail.version_at(self.date_version_client)
  end

  def generate_new_devis_number
    Date.today.to_formatted_s(:number) + '-' + self.user.dernier_numero_devis.to_s.rjust(6, '0')
  end

  def update_from_nested_params(params)
    if !params[:client_attributes].nil?
      if params[:client_attributes][:id] == ""
        # Creating a new associated client
        self.client = self.user.clients.build() #Client.new
        self.client.assign_attributes(params[:client_attributes])
        self.client.taxe = self.taxe
        params.delete :client_attributes
      elsif params[:client_attributes][:id] != self.client.id
        # Changing the associated client
        client = Client.find(params[:client_attributes][:id])
        client.assign_attributes(params[:client_attributes])
        params.delete :client_attributes
        self.client = client
      end
    end
    return self.update(params)
  end

  def duplicate
    replica = dup
    devis_lignes.each do |devis_ligne|
      replica.devis_lignes << devis_ligne.dup
    end
    replica.date    = Date.today
    replica.numero  = replica.generate_new_devis_number
    replica
  end

  private

    def define_number_devis
      if (self.numero.nil? || self.numero == '')
        self.numero = generate_new_devis_number
        self.user.dernier_numero_devis += 1
        self.user.save
      end
    end

    def define_client_updated_at
      if !self.client.nil?
        if self.new_record? && !self.client.changed?
          self.date_version_client = self.client.updated_at
        end
        if self.client.changed?
          self.client.updated_at = Time.now.utc
          self.date_version_client = self.client.updated_at
        end
      end
    end
end

app/controllers/devis_controller.rb
class DevisController < ApplicationController
  before_action :set_devi, only: %i[ show edit update destroy ]
  before_action :set_modele, only: %i[ new create ]
  before_action :set_creating_new, only: %i[ new create duplicate ]

  # GET /devis or /devis.json
  def index
    @devis = current_user.devis.order(date: "DESC", numero: "DESC")
  end

  # GET /devis/1 or /devis/1.json
  def show
    filename = "Devis #{@devi.numero} - #{@devi.client.nom} - #{montant_pour_pdf(@devi.montant_ttc)}" #Devis 20210203-000119 - MAIF - 11 556,00e
    respond_to do |format|
      format.html
      format.pdf do
        render  show_as_html: params.key?('debug'),
                # save_to_file: Rails.root.join('sauvegardes/factures', "#{filename}.pdf"),
                pdf: filename,
                disposition: 'attachment',
                template: "devis/show",
                layout: "pdf",
                footer:  {
                  font_size: 8,
                  spacing: 20,
                  center: @devi.mention_legale + '

' + 'Page [page] / [topage]'
                },
                margin:  {
                            top: 10,
                            bottom: 30
                          }
      end
    end
  end

  # GET /devis/new
  def new
    @devi = current_user.devis.build_with_model(@modele_selectionne)
  end

  # GET /devis/1/edit
  def edit
    @devi.client = @devi.client_current_version
  end

  # POST /devis or /devis.json
  def create
    @devi = current_user.devis.build_from_create_params(devi_params)

    respond_to do |format|
      if @devi.save
        format.html { redirect_to edit_devi_path(@devi) }
        format.json { render :show, status: :created, location: @devi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @devi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devis/1 or /devis/1.json
  def update
    respond_to do |format|
      if @devi.update_from_nested_params(devi_params)
        format.html { redirect_to edit_devi_path(@devi) }
        format.json { render :show, status: :ok, location: @devi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @devi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devis/1 or /devis/1.json
  def destroy
    @devi.destroy
    respond_to do |format|
      format.html { redirect_to devis_url }
      format.json { head :no_content }
    end
  end

  # GET /devis/1/duplicate or /devis/1.json/duplicate
  def duplicate
    @devis_source = Devi.find(params[:id])
    @devi = @devis_source.duplicate

    respond_to do |format|
      format.html { render :new }
      format.json { render json: @devi.errors, status: :unprocessable_entity }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devi
      @devi = Devi.find(params[:id])
    end

    def set_modele
      if params[:with_model]
        @modele_selectionne = current_user.document_modeles.find(params[:with_model])
      else
        @modele_selectionne = current_user.document_modeles.where(defaut: true).first
      end
    end

    def set_creating_new
      @creating_new = true
    end

    # Only allow a list of trusted parameters through.
    def devi_params
      params[:devi][:client_attributes][:nom] = params[:devi][:client_attributes].delete :client unless params[:devi][:client_attributes].nil?
      params.require(:devi).permit(:type_document, :contrast_color, :date, :designation, :montant_ht, :montant_tva, :montant_ttc, :est_brouillon, :pdf, :taxe_id, :devis_statut_id, :client_id, :coordonnees_societe, :coordonnees_societe, :logo, :date_validite, :mention1_texte, :mention2_texte, :mention3_texte, :mention_legale, devis_lignes_attributes: [:id, :designation, :montant_ht, :_destroy], client_attributes: [:id, :nom, :adresse, :code_postal, :ville, :pays, :numero_tva_intracommunautaire, :email, :telephone, :special, :prestation_hypnose, :prestation_boutique, :prestation_ux])
    end

    def montant_pour_pdf(nombre)
      ActionController::Base.helpers.number_to_currency(nombre, unit: "e", separator: ",", delimiter: " ", format: "%n%u", negative_format: "-%n%u")
    end
end

app/helpers/devis_helper.rb
module DevisHelper
  # This method creates a link with `data-id` `data-fields` attributes. These attributes are used to create new instances of the nested fields through Javascript.
  def link_to_add_devis_line(name, f, association)
      new_object = f.object.send(association).klass.new
      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|
          render('devis/partials/' + association.to_s.singularize + "_fields_form", f: builder)
      end
      link_to(name, '#', class: "add_fields button", data: {id: id, fields: fields.gsub("\n", "")})

  end

  def links_to_choose_devis_model(models, default_model)
    output = ""
    models.each do |modele|
      css_class = "button"
      if default_model == modele
        css_class += " is-active"
      end
      output += '<p class="control">'
      output += link_to(modele.nom, new_devi_path(:with_model => modele.id), class: css_class)
      output += '</p>'
    end
    output.html_safe
  end

  def date_pour_devis(devi)

    output = ""
    output += "<div class='is-size-5'>" + devi.date.strftime("%d") + '</div>'
    output += "<div class='is-size-7'>" + devi.date.strftime("%^b.")
    output += devi.date.strftime(" %y") unless devi.date.year == Date.today.year
    output += '</div>'
    # devi.date.strftime("%d")
    output.html_safe
  end

  def numero_pour_devis(devi)
    "N°#{devi.numero}"
  end

  def statut_pour_devis(devi)
    render "devis/partials/devis_statut_selecteur", devi: devi
  end

end

app/views/devis/_form.html.erb
<style type="text/css">
  .has-bg-primary-color {
    background-color: <%= @devi.contrast_color %> !important;
    color: #ffffff !important;
  }
  .has-text-primary-color {
    color: <%= @devi.contrast_color %> !important;
  }
</style>
<%= form_with(model: devi, html: {autocomplete: "off"}) do |form| %>
  <div class="panel devis-actions">
    <div class="panel-block">
        <div class="buttons">
          <% if @creating_new %>
            <%= form.button "Créer le devis", name: 'commit', value: "devi", class: "button is-primary is-fullwidth" %>
          <% else %>
            <%= form.button "Enregistrer", name: 'commit', value: "devi", class: "button is-primary is-fullwidth" %>
            <%= link_to "Générer le PDF", devi_path(@devi, format: :pdf), class: "button is-fullwidth" %>
            <%= link_to 'Supprimer', devi_path(@devi), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, :method => :delete, class: "button is-danger is-fullwidth" %>
            <hr class="buttons-divider">
            <%= link_to "Dupliquer", duplicate_devi_path(@devi), class: "button is-fullwidth" %>
          <% end %>
      </div>
    </div>
  </div>

    <div class="card devis-feuille">
      <% if @creating_new %>
        <%= form.hidden_field :devi_statut_id%>
      <% else %>
        <%= statut_pour_devis(@devi) %>
      <% end %>

        <% if devi.errors.any? %>
          <div class="notification is-danger">
            <h2 class="is-size-5"><%= pluralize(devi.errors.count, "error") %> prohibited this devi from being saved:</h2>
            <div class="content">
            <ul>
              <% devi.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
            </div>
          </div>
        <% end %>

        <div class="tile is-ancestor">
          <div class="tile is-parent is-5">
            <div class="logo has-text-centered">
                <%= image_tag(@devi.logo) %>
                <%= form.hidden_field :logo %>
                <%= form.hidden_field :contrast_color %>
            </div>
          </div>
          <div class="tile is-parent is-2"></div>
          <div class="tile is-parent is-5"></div>
        </div>
        <div class="tile is-ancestor">
          <div class="tile is-parent is-5">
            <div class="fournisseur">
              <%= render "devis/partials/fournisseur_form", form: form %>
            </div>
          </div>
          <div class="tile is-parent is-2"></div>
          <div class="tile is-parent is-5">
            <div class="tile is-child">
              <div class="client">
                <%= form.fields_for :client do |client_form| %>
                  <%= render "devis/partials/client_form", form: client_form %>
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <div class="contenu-principal">
          <%= render "devis/partials/entete_form", form: form %>

          <div class="devis-lignes">
            <table class="table is-fullwidth is-narrow" id="table_lignes_devis">
              <thead>
                <tr>
                  <th class="has-text-left has-bg-primary-color" colspan="2">Désignation</th>
                  <th class="is-narrow has-bg-primary-color">Montant HT</th>
                </tr>
              </thead>
              <tbody>
              <%= form.fields_for :devis_lignes do |devis_ligne| %>
                  <%= render "devis/partials/devis_ligne_fields_form", f: devis_ligne %>
              <% end %>
              </tbody>
              <tfoot>
                <%= render "devis/partials/pied_form", form: form %>
              </tfoot>
            </table>
          </div>

          <div class="devi-mentions">
            <%= render "devis/partials/mentions_form", form: form %>
          </div>

        </div>

  </div>
<% end %>

app/views/devis/debug.html.erb
<code>
  <%= @params.inspect %>
</code>

app/views/devis/edit.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(devis_path) %>
  <%= page_title("Modifier un devis") %>
</nav>

<div class="devis-form">
    <%= render 'form', devi: @devi %>
</div>

app/views/devis/index.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to_root() %>
  <%= page_title("Devis") %>
</nav>

<div class="action-buttons">
    <div class="field is-grouped">
      <p class="control">
        <%= link_to 'Nouveau devis', new_devi_path, class: "button is-primary" %>
      </p>
    </div>
</div>

<table class="table is-fullwidth is-hoverable " >
  <thead>
    <tr>
      <th class="has-text-left">Date</th>
      <th class="has-text-left">Numéro de devis</th>
      <th class="has-text-left">État</th>
      <th class="has-text-left">Nom client</th>
      <th class="has-text-left">Désignation</th>
      <th class="has-text-left">Montant HT (€)</th>
      <th class="has-text-left">TVA (€)</th>
      <th class="has-text-left">Montant TTC (€)</th>
      <th class="has-text-left"></th>
    </tr>
  </thead>

  <tbody>
    <% @devis.each do |devi| %>
      <tr class='clickable-row is-clickable' data-href='<%= url_for edit_devi_path(devi)%>'>
        <td class="has-text-centered"><%= date_pour_devis(devi) %></td>
        <td class="is-vcentered"><%= numero_pour_devis(devi) %></td>
        <td class="is-vcentered"><%= statut_pour_devis(devi) %></td>
        <td class="is-vcentered"><%= devi.client.nom %></td>
        <td class="is-vcentered"><%= devi.designation %></td>
        <td class="is-vcentered has-text-right"><%= montant_humanise(devi.montant_ht) %></td>
        <td class="is-vcentered has-text-right"><%= montant_humanise(devi.montant_tva) %></td>
        <td class="is-vcentered has-text-right"><%= montant_humanise(devi.montant_ttc) %></td>
        <td class="is-vcentered">
            <a href="<%= devi_path(devi, format: :pdf) %>" class="button is-small">PDF</a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devis/new.html.erb
<nav class="navbar is-light is-fixed-top">
  <%= back_link_to(devis_path) %>
  <%= page_title("Nouveau devis") %>
</nav>

<div class="action-buttons">
    <div class="field is-grouped">
        <%= links_to_choose_devis_model(current_user.document_modeles.order(:nom), @modele_selectionne) %>
    </div>
</div>

<div class="devis-form">
    <%= render 'form', devi: @devi %>
</div>

app/views/devis/show.html.erb
<style type="text/css">
  .has-bg-primary-color {
    background-color: <%= @facture.contrast_color %> !important;
    color: #ffffff !important;
  }
  .has-text-primary-color {
    color: <%= @facture.contrast_color %> !important;
  }
</style>

<div class="card content facture-feuille">

  <div class="tile is-ancestor">
    <div class="tile is-parent is-5">
        <div class="logo has-text-centered">
            <%= wicked_pdf_image_tag(@facture.logo, srcset: { "2x-#{@facture.logo}" => "2x" }) %>
        </div>
    </div>
    <div class="tile is-parent is-2"></div>
    <div class="tile is-parent is-5"></div>
  </div>
  <div class="tile is-ancestor">
    <div class="tile is-parent is-5">
        <%= simple_format(@facture.coordonnees_societe, class: "has-text-left coordonnees") %>
    </div>
    <div class="tile is-parent is-2"></div>
    <div class="tile is-parent is-5">
      <div class="tile is-child">
        <%= render "factures/partials/client_show" %>
      </div>
    </div>
  </div>

  <div class="contenu-principal">
    <%= render "factures/partials/entete_show" %>
    <div class="facture-lignes">
      <table class="table is-fullwidth is-narrow" id="table_lignes_facture">
        <thead>
          <tr>
            <th class="has-text-left has-bg-primary-color" colspan="2">Désignation</th>
            <th class="is-narrow has-bg-primary-color">Montant HT</th>
          </tr>
        </thead>
        <tbody>
        <% @facture.facture_lignes.each do |facture_ligne| %>
            <%= render "factures/partials/facture_ligne_show", facture_ligne: facture_ligne %>
        <% end %>
        </tbody>
        <tfoot>
          <%= render "factures/partials/pied_show" %>
        </tfoot>
      </table>
    </div>

    <div class="facture-mentions">
      <%= render "factures/partials/mentions_show" %>
    </div>

  </div>

</div>

app/views/devis/show.pdf.erb
<style type="text/css">
  .has-bg-primary-color {
    background-color: <%= @devi.contrast_color %> !important;
    color: #ffffff !important;
  }
  .has-text-primary-color {
    color: <%= @devi.contrast_color %> !important;
  }
</style>

<div class="content devis-feuille">
  <table class="table is-narrow">
    <tr>
      <td>
        <div class="logo has-text-centered">
            <%= image_tag wicked_pdf_asset_base64(@devi.logo) %>
        </div>
      </td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td>
        <div class="has-text-left fournisseur"><%= simple_format(@devi.coordonnees_societe) %></div>
      </td>
      <td></td>
      <td>
        <div class="client"><%= render partial: "devis/partials/client_show", formats: :html %></div>
      </td>
    </tr>
  </table>

  <div class="contenu-principal">
    <%= render partial: "devis/partials/entete_show", formats: :html %>
    <div class="devi-lignes">
      <table class="table is-fullwidth is-narrow" id="table_lignes_devi">
        <thead>
          <tr>
            <th class="has-text-left has-bg-primary-color" colspan="2">Désignation</th>
            <th class="is-narrow has-bg-primary-color">Montant HT</th>
          </tr>
        </thead>
        <tbody>
        <% @devi.devis_lignes.each do |devis_ligne| %>
            <%= render partial: "devis/partials/devis_ligne_show", formats: :html, object: devis_ligne, as: 'devis_ligne' %>
        <% end %>
        </tbody>
        <tfoot>
          <%= render partial: "devis/partials/pied_show", formats: :html %>
        </tfoot>
      </table>
    </div>

    <div class="devi-mentions">
      <%= render partial: "devis/partials/mentions_show", formats: :html %>
    </div>

  </div>

  </div>